version: '3.3'
services:
  web:
    build:
      context: ./php
      dockerfile: DockerFile
    container_name: php
    volumes:
      - ./php:/var/www/html/
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '8000:80'
    networks:
      - jade
  db:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2022
      MYSQL_DATABASE: avaliacao
      MYSQL_PASSWORD: 123456
    ports:
      - '5200:3306'
    networks:
      - jade

networks:
  jade:
    driver: bridge